// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmzePw-GxQlJNYIv0mLP25DxlDSB3kIXo',
    appId: '1:839285865284:web:5a483795040cc6720e3511',
    messagingSenderId: '839285865284',
    projectId: 'evenly-c20',
    authDomain: 'evenly-c20.firebaseapp.com',
    storageBucket: 'evenly-c20.firebasestorage.app',
    measurementId: 'G-9P6M2263SC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnp0pRV73Ctb5FiTvwMxNTFVxDO-dp9Jg',
    appId: '1:839285865284:android:bed8246bfec073ed0e3511',
    messagingSenderId: '839285865284',
    projectId: 'evenly-c20',
    storageBucket: 'evenly-c20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAZSnRokRhiPSYKJLbfjXB-QSJlrPdqSg',
    appId: '1:839285865284:ios:350dc3934905ba860e3511',
    messagingSenderId: '839285865284',
    projectId: 'evenly-c20',
    storageBucket: 'evenly-c20.firebasestorage.app',
    iosBundleId: 'com.route.evently.eventlyC20Dokki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAZSnRokRhiPSYKJLbfjXB-QSJlrPdqSg',
    appId: '1:839285865284:ios:350dc3934905ba860e3511',
    messagingSenderId: '839285865284',
    projectId: 'evenly-c20',
    storageBucket: 'evenly-c20.firebasestorage.app',
    iosBundleId: 'com.route.evently.eventlyC20Dokki',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmzePw-GxQlJNYIv0mLP25DxlDSB3kIXo',
    appId: '1:839285865284:web:b1f99667192b6e070e3511',
    messagingSenderId: '839285865284',
    projectId: 'evenly-c20',
    authDomain: 'evenly-c20.firebaseapp.com',
    storageBucket: 'evenly-c20.firebasestorage.app',
    measurementId: 'G-K1QJS4PEMQ',
  );
}
